export const PHOTO_ASPECT_WIDTH = 4
export const PHOTO_ASPECT_HEIGHT = 5
export const PHOTO_ASPECT_RATIO = PHOTO_ASPECT_WIDTH / PHOTO_ASPECT_HEIGHT
export const PHOTO_OUTPUT_WIDTH = 960
export const PHOTO_OUTPUT_HEIGHT = Math.round(
  PHOTO_OUTPUT_WIDTH * (PHOTO_ASPECT_HEIGHT / PHOTO_ASPECT_WIDTH),
)
